Modify 3gpictl

diff --git a/3gpictl b/3gpictl
--- a/3gpictl
+++ b/3gpictl
@@ -4,7 +4,7 @@
 # control 3gpi module script
 # 
 
-VERSION="3gpictl version 0.2"
+VERSION="3gpictl version 0.3"
 
 USAGE="Usage: 3gpictl [OPTION]
 
@@ -53,34 +53,48 @@ stat_gpio ()
 }
 
 #
-# Usage: ctl_gpio [CONDITION] [GPIO_PIN] [TOGGLE_INTERVAL]
+# Usage: ctl_gpio [CONDITION] [GPIO_PIN] [TOGGLE_INTERVAL] [TIMEOUT]
 #
 ctl_gpio ()
 {
-    STATUS=$(stat_gpio $STATUS_PIN)
     PORT="/sys/class/gpio/gpio${2}/value"
- 
-    if [ $? -ne 0 ]
-    then
-        echo $STATUS
-        return 1
-    fi
 
-    if [ $STATUS = $1 ]
-    then
-        echo "already power ${1}"
-        return 1
-    fi
+    for i in `seq 0 $4`
+    do 
+        STATUS=$(stat_gpio $STATUS_PIN)
+        
+        if [ $? -ne 0 ]
+        then
+            echo $STATUS
+            return 1
+        fi
+        
+        if [ $STATUS = $1 ]
+        then
+            if [ $i -eq 0 ]
+            then
+                echo "already power ${1}"
+            fi
+            return 0
+        fi
+        
+        if [ ! -w $PORT ]
+        then
+            echo "cannot access ${PORT}"
+            return 1
+        fi
 
-    if [ ! -w $PORT ]
-    then
-        echo "cannot access ${PORT}"
-        return 1
-    fi
-
-    echo 1 > $PORT
-    sleep $3
-    echo 0 > $PORT
+        if [ $i -eq 0 ]
+        then        
+            echo 1 > $PORT
+            sleep $3
+            echo 0 > $PORT
+        fi
+    done
+    
+    echo "timeout power ${1}"
+    
+    return 1
 }
 
 #
@@ -102,13 +116,13 @@ ctl_gps ()
 #
 case $1 in
 --poweron)
-    ctl_gpio "on" $POWER_PIN 3
+    ctl_gpio "on" $POWER_PIN 3 30
     ;;
 --poweroff)
-    ctl_gpio "off" $POWER_PIN 3
+    ctl_gpio "off" $POWER_PIN 3 30
     ;;
 --reset)
-    ctl_gpio "off" $RESET_PIN 1
+    ctl_gpio "off" $RESET_PIN 1 30
     ;;
 --status)
     stat_gpio $STATUS_PIN
